name: agendar_cc_flutter
description: A mobile App to schedule the PT Citizen Card and more....

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  flutter_localizations:
    sdk: flutter
  geolocator: ^7.6.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_maps: ^5.3.0
  google_maps_flutter: ^2.0.6
  grouped_list: ^4.1.0
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  table_calendar: ^3.0.2
  time_range_selector:
    path: ./packages/time_range_selector
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_ios: "docs/images/icon.png"
  image_path_android: "docs/images/icon.png"

flutter:
  uses-material-design: true
