name: agendar_cc_flutter
description: A mobile App to schedule the PT Citizen Card and more....

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_inappwebview: ^5.3.2

flutter:
  uses-material-design: true
