name: agendar_cc_flutter
description: A mobile App to schedule the PT Citizen Card and more....

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^5.0.0
  google_maps_flutter: ^2.0.6
  flutter_inappwebview: ^5.3.2
  google_fonts: ^2.1.0
  uuid: ^3.0.4
  get_it: ^7.2.0
  grouped_list: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
